import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { IconName } from '@fortawesome/free-solid-svg-icons'
import Inputs from '../components/Inputs'
import Menus from '../components/Menus'
import Footers from '../components/Footers'
import Tags from '../components/Tags'
import WindStormRain from '../components/WeatherIcons/WindStormRain'
import WindStorm from '../components/WeatherIcons/WindStorm'
import Wind from '../components/WeatherIcons/Wind'
import Umbrella from '../components/WeatherIcons/Umbrella'
import Temperature from '../components/WeatherIcons/Temperature'
import Sunny from '../components/WeatherIcons/Sunny'
import Snow from '../components/WeatherIcons/Snow'
import Moon from '../components/WeatherIcons/Moon'
import Drop from '../components/WeatherIcons/Drop'
import Cloudy from '../components/WeatherIcons/Cloudy'
import Cloud from '../components/WeatherIcons/Cloud'
import Bolt from '../components/WeatherIcons/Bolt'
import Warning from '../components/UsersIcons/Warning'
import Time from '../components/UsersIcons/Time'
import Remove from '../components/UsersIcons/Remove'
import More from '../components/UsersIcons/More'
import Info from '../components/UsersIcons/Info'
import Confirm from '../components/UsersIcons/Confirm'
import Close from '../components/UsersIcons/Close'
import UserArrowUp from '../components/UsersIcons/UserArrowUp'
import UserArrowRight from '../components/UsersIcons/UserArrowRight'
import UserArrowLeft from '../components/UsersIcons/UserArrowLeft'
import UserArrowDown from '../components/UsersIcons/UserArrowDown'
import UserAdd from '../components/UsersIcons/UserAdd'
import Workflow from '../components/StatisticsIcons/Workflow'
import Speed from '../components/StatisticsIcons/Speed'
import Chart1 from '../components/StatisticsIcons/Chart1'
import Chart2 from '../components/StatisticsIcons/Chart2'
import Funnel from '../components/StatisticsIcons/Funnel'
import CircleChart from '../components/StatisticsIcons/CircleChart'
import Statistics7 from '../components/StatisticsIcons/Statistics7'
import Statistics6 from '../components/StatisticsIcons/Statistics6'
import Statistics5 from '../components/StatisticsIcons/Statistics5'
import Statistics4 from '../components/StatisticsIcons/Statistics4'
import Statistics3 from '../components/StatisticsIcons/Statistics3'
import Statistics2 from '../components/StatisticsIcons/Statistics2'
import SportYard from '../components/SportIcons/SportYard'
import SportWinner1 from '../components/SportIcons/SportWinner1'
import SportWinner from '../components/SportIcons/SportWinner'
import SportSoccerField from '../components/SportIcons/SportSoccerField'
import SportSmallDumbbell from '../components/SportIcons/SportSmallDumbbell'
import SportRugby from '../components/SportIcons/SportRugby'
import SportJumpRope from '../components/SportIcons/SportJumpRope'
import SportGolf from '../components/SportIcons/SportGolf'
import SportFootball from '../components/SportIcons/SportFootball'
import SportDumbbell from '../components/SportIcons/SportDumbbell'
import SportBottle from '../components/SportIcons/SportBottle'
import SportBasketball from '../components/SportIcons/SportBasketball'
import ShoppingWallet from '../components/ShoppingIcon/ShoppingWallet'
import ShoppingTShirt from '../components/ShoppingIcon/ShoppingTShirt'
import ShoppingSign from '../components/ShoppingIcon/ShoppingSign'
import ShoppingRack from '../components/ShoppingIcon/ShoppingRack'
import ShoppingPerfume from '../components/ShoppingIcon/ShoppingPerfume'
import ShoppingHouse from '../components/ShoppingIcon/ShoppingHouse'
import ShoppingEscalator from '../components/ShoppingIcon/ShoppingEscalator'
import ShoppingDiscount from '../components/ShoppingIcon/ShoppingDiscount'
import ShoppingCode from '../components/ShoppingIcon/ShoppingCode'
import ShoppingCashRegister from '../components/ShoppingIcon/ShoppingCashRegister'
import ShoppingBox from '../components/ShoppingIcon/ShoppingBox'
import ShoppingBag from '../components/ShoppingIcon/ShoppingBag'
import SecurityUnsecured from '../components/SecurityIcons/SecurityUnsecured'
import SecurityUnlocked from '../components/SecurityIcons/SecurityUnlocked'
import SecurityShield from '../components/SecurityIcons/SecurityShield'
import SecuritySecuredProfile from '../components/SecurityIcons/SecuritySecuredProfile'
import SecuritySecuritySafety from '../components/SecurityIcons/SecuritySecuritySafety'
import SecuritySafe from '../components/SecurityIcons/SecuritySafe'
import SecurityLocked from '../components/SecurityIcons/SecurityLocked'
import SecurityKey from '../components/SecurityIcons/SecurityKey'
import SecurityHiddenCamera from '../components/SecurityIcons/SecurityHiddenCamera'
import SecurityFingerPrint from '../components/SecurityIcons/SecurityFingerPrint'
import SecurityCamera from '../components/SecurityIcons/SecurityCamera'
import SecurityAlarm from '../components/SecurityIcons/SecurityAlarm'
import ChevronDown from '../components/ChevronIcons/ChevronDown'
import ChevronLeftRight from '../components/ChevronIcons/ChevronLeftRight'
import ChevronLeft from '../components/ChevronIcons/ChevronLeft'
import ChevronTop from '../components/ChevronIcons/ChevronTop'
import ChevronRight from '../components/ChevronIcons/ChevronRight'
import ChevronTopBottom from '../components/ChevronIcons/ChevronTopBottom'
import Buttons from '../components/Buttons'
import Checkboxes from '../components/Checkboxes'
import Product from '../components/Products/Product'
import CategoryMenu from '../components/CategoryMenu'
import Brand from '../components/Brand'
import ProductWithCategory from '../components/Products/ProductWithCategory'
import Selects from '../components/Selects'
import Heading from '../components/Navigations/Heading'
import Avatar from '../components/Quotes/Avatar'
import Search from '../components/Search'
import HeaderDefault from '../components/Headers/HeaderDefault'
import ProductWithTitle from '../components/Products/ProductWithTitle'


export default function Home() {
  return (
    // Home Page Design
    <div className='flex items-center flex-col'>
      
      {/* Products with Category */}
        <ProductWithCategory imageUrl1={'/images/imperatorCarrot.jfif'} imageAlt1='Imperator Carrot' imageUrl2='/images/nectarCarrot.jfif' imageAlt2='Nectar Red Carrots' imageUrl3='/images/nutriRedCarrot.jfif' imageAlt3='Nutri Red Carrot' categoryItem1='Kitchen' categoryItem2='Meat and fish' categoryItem3='Special nutrition'
        categoryItem4='Pharmacy' categoryItem5='Baby' href1='./kitchen' href2='./meat' href3='./nutrition' href4='./pharmacy'
        href5='./babyproduct' productTitle1='Imperator Carrot' productDescription1='Fresh imperator carrot. Best for the dish. Grows best in summer.'
        productPrice1='13.48 USD' tagLabel1='- 36 %' productTitle2='Nectar Carrots' productDescription2='Fresh nectar carrots. Have a sweet, juicy taste.'
        productPrice2='30.56 USD' productOldPrice1='50.77 USD' productTitle3='NUTRI-Red-Carrots' productDescription3='Fresh and Juicy nutri-red carrots. Best for salad and halwa.'
        productPrice3='130 USD' productOldPrice2='151.02 USD' tagLabel2='- 36 %' buttonLabel='More products' style="Border" categoryTitle='Best selling products' />
        <ProductWithCategory  imageUrl1='/images/freshTomatoes.jfif' imageAlt1='Imperator Carrot' imageUrl2='/images/americanTomato.jfif' imageAlt2='Nectar Red Carrots' imageUrl3='/images/raddishPods.jfif' imageAlt3='Raddish Pods' categoryItem1='Fresh Tomatoes' categoryItem2='Tomatoes' categoryItem3='Potatoes'
        categoryItem4='Chicken' categoryItem5='Beef' href1='./tomatoes' href2='./meat' href3='./nutrition' href4='./pharmacy'
        href5='./babyproduct' productTitle1='Tomatoes' productDescription1='Fresh Tomatoes. Best for the dish. Grows best in summer.'
        productPrice1='25.18 USD' tagLabel1='- 36 %' productTitle2='American Tomatoes' productDescription2='Fresh American Tomatoes. Have a sweet, juicy taste.'
        productPrice2='115.00 USD' productOldPrice1='144.72 USD' productTitle3='Raddish Pods' productDescription3='Fresh Raddish pods. Best for the winter dishes with qeema.'
        productPrice3='130 USD' productOldPrice2='151.02 USD' tagLabel2='- 36 %' buttonLabel='More products' style="Border" categoryTitle='More from Farmers' />
        {/* Product with Title */}
        <ProductWithTitle title='Featured Products' buttonLabel='see all' imageUrl1='/images/redApple.jfif' imageAlt1='Red Apple' imageUrl2='/images/greenchili.jfif' imageAlt2='Green Chili' imageUrl3='/images/redChiliPlant.jfif' imageAlt3='Red Chili plant' imageUrl4='/images/BlackGrapes.jfif' imageAlt4='Black Grapes'
        productTitle1='Red Apple' productDescription1='Fresh and Juicy apples. Best for milkshakes and mix chat' productPrice1='12.00 USD' productTitle2='Green Chili' productDescription2='Green and Fresh chili' productPrice2='34.88 USD' productTitle3='Red Chili Plant' productDescription3='Seeds and Plant of red chili' 
        productPrice3='2.78 USD' tagLabel='- 36 %' productOldPrice='3.12 USD' productTitle4='Russian Black Grapes' productDescription4='Fresh and Juicy Russian black grapes are here. ' productPrice4='77.50 USD' />
        {/* Footer */}
        <Footers variant="White" label='Copyright © 2022        Designed with ❤️ by ebridge.tech' type="Default"/>
    </div>
  )
}
